### PR TITLE
Update example config files to make vagrant usage easier

### PR DESCRIPTION
**Pull request by conord33**
Updated to example config files so they can just be copied to get vagrant working.

### CODE REVIEW

**Comment by wtlangford** [comment]
The tabs v spaces fight is real.

**Comment by conord33** [comment]
haha i dont work for a compression company

**Comment by wtlangford** [comment]
I have no complaints about the changes, but now there are some json files with tabs and others with spaces and the lack of consistency _is_ upsetting to me.

**Comment by conord33** [comment]
okay is better now

**Pull request merged**
